var EMOJIS = [
    { emoji: "😀", name: "grinning face", keywords: "happy smile laugh" },
    { emoji: "😃", name: "grinning face with big eyes", keywords: "happy smile excited" },
    { emoji: "😄", name: "grinning face with smiling eyes", keywords: "happy joy laugh" },
    { emoji: "😁", name: "beaming face with smiling eyes", keywords: "grin pleased" },
    { emoji: "😆", name: "grinning squinting face", keywords: "laugh lol amused" },
    { emoji: "😅", name: "grinning face with sweat", keywords: "relief awkward laugh" },
    { emoji: "🤣", name: "rolling on the floor laughing", keywords: "rofl lol laugh" },
    { emoji: "😂", name: "face with tears of joy", keywords: "lol cry laugh" },
    { emoji: "🙂", name: "slightly smiling face", keywords: "gentle smile" },
    { emoji: "🙃", name: "upside-down face", keywords: "sarcasm silly" },
    { emoji: "😉", name: "winking face", keywords: "flirt playful" },
    { emoji: "😊", name: "smiling face with smiling eyes", keywords: "blush pleased" },
    { emoji: "😇", name: "smiling face with halo", keywords: "angel innocent" },
    { emoji: "🥰", name: "smiling face with hearts", keywords: "love adore" },
    { emoji: "😍", name: "smiling face with heart-eyes", keywords: "love crush" },
    { emoji: "🤩", name: "star-struck", keywords: "wow excited" },
    { emoji: "😘", name: "face blowing a kiss", keywords: "love kiss" },
    { emoji: "😗", name: "kissing face", keywords: "kiss affection" },
    { emoji: "😚", name: "kissing face with closed eyes", keywords: "kiss shy" },
    { emoji: "😙", name: "kissing face with smiling eyes", keywords: "kiss smile" },
    { emoji: "🥲", name: "smiling face with tear", keywords: "proud moved" },
    { emoji: "😋", name: "face savoring food", keywords: "yum tasty" },
    { emoji: "😛", name: "face with tongue", keywords: "playful silly" },
    { emoji: "😜", name: "winking face with tongue", keywords: "joke teasing" },
    { emoji: "🤪", name: "zany face", keywords: "crazy goofy" },
    { emoji: "😝", name: "squinting face with tongue", keywords: "tease silly" },
    { emoji: "🤑", name: "money-mouth face", keywords: "rich cash" },
    { emoji: "🤗", name: "hugging face", keywords: "hug welcome" },
    { emoji: "🤭", name: "face with hand over mouth", keywords: "oops giggle" },
    { emoji: "🤫", name: "shushing face", keywords: "quiet secret" },
    { emoji: "🤔", name: "thinking face", keywords: "hmm question" },
    { emoji: "🫡", name: "saluting face", keywords: "respect yes" },
    { emoji: "🤨", name: "face with raised eyebrow", keywords: "skeptical doubt" },
    { emoji: "😐", name: "neutral face", keywords: "meh blank" },
    { emoji: "😑", name: "expressionless face", keywords: "blank unimpressed" },
    { emoji: "😶", name: "face without mouth", keywords: "speechless quiet" },
    { emoji: "🫥", name: "dotted line face", keywords: "disappear invisible" },
    { emoji: "😏", name: "smirking face", keywords: "smug sly" },
    { emoji: "😒", name: "unamused face", keywords: "annoyed displeased" },
    { emoji: "🙄", name: "face with rolling eyes", keywords: "eyeroll annoyed" },
    { emoji: "😬", name: "grimacing face", keywords: "awkward cringe" },
    { emoji: "😮‍💨", name: "face exhaling", keywords: "sigh relief tired" },
    { emoji: "🤥", name: "lying face", keywords: "lie pinocchio" },
    { emoji: "😌", name: "relieved face", keywords: "calm peaceful" },
    { emoji: "😔", name: "pensive face", keywords: "sad thoughtful" },
    { emoji: "😪", name: "sleepy face", keywords: "tired drowsy" },
    { emoji: "🤤", name: "drooling face", keywords: "want hungry" },
    { emoji: "😴", name: "sleeping face", keywords: "sleep zzz" },
    { emoji: "🫵", name: "index pointing at the viewer", keywords: "you point attention" },
    { emoji: "🤐", name: "zipper-mouth face", keywords: "sealed secret" },
    { emoji: "🥴", name: "woozy face", keywords: "dizzy drunk" },
    { emoji: "🤢", name: "nauseated face", keywords: "sick gross" },
    { emoji: "🤮", name: "face vomiting", keywords: "puke sick" },
    { emoji: "🤧", name: "sneezing face", keywords: "cold achoo" },
    { emoji: "🥵", name: "hot face", keywords: "heat spicy" },
    { emoji: "🥶", name: "cold face", keywords: "freezing ice" },
    { emoji: "🥳", name: "partying face", keywords: "celebration birthday" },
    { emoji: "🤯", name: "exploding head", keywords: "mind blown wow" },
    { emoji: "😎", name: "smiling face with sunglasses", keywords: "cool chill" },
    { emoji: "🤓", name: "nerd face", keywords: "geek smart" },
    { emoji: "🧐", name: "face with monocle", keywords: "inspect fancy" },
    { emoji: "😕", name: "confused face", keywords: "confused unsure" },
    { emoji: "🫤", name: "face with diagonal mouth", keywords: "meh uncertain" },
    { emoji: "😟", name: "worried face", keywords: "concern anxious" },
    { emoji: "🙁", name: "slightly frowning face", keywords: "sad upset" },
    { emoji: "☹️", name: "frowning face", keywords: "sad unhappy" },
    { emoji: "😮", name: "face with open mouth", keywords: "surprised wow" },
    { emoji: "😯", name: "hushed face", keywords: "quiet surprise" },
    { emoji: "😲", name: "astonished face", keywords: "shock amazed" },
    { emoji: "😳", name: "flushed face", keywords: "embarrassed blush" },
    { emoji: "🥺", name: "pleading face", keywords: "beg puppy eyes" },
    { emoji: "🥹", name: "face holding back tears", keywords: "moved emotional" },
    { emoji: "😦", name: "frowning face with open mouth", keywords: "worried alarmed" },
    { emoji: "😧", name: "anguished face", keywords: "pain stressed" },
    { emoji: "😨", name: "fearful face", keywords: "scared fear" },
    { emoji: "😰", name: "anxious face with sweat", keywords: "nervous stress" },
    { emoji: "😥", name: "sad but relieved face", keywords: "phew sad" },
    { emoji: "😢", name: "crying face", keywords: "cry sad tear" },
    { emoji: "😭", name: "loudly crying face", keywords: "sob bawl" },
    { emoji: "😱", name: "face screaming in fear", keywords: "scream horror" },
    { emoji: "😖", name: "confounded face", keywords: "frustrated upset" },
    { emoji: "😣", name: "persevering face", keywords: "struggle endure" },
    { emoji: "😞", name: "disappointed face", keywords: "sad letdown" },
    { emoji: "😓", name: "downcast face with sweat", keywords: "work hard" },
    { emoji: "😩", name: "weary face", keywords: "tired exhausted" },
    { emoji: "😫", name: "tired face", keywords: "exhausted upset" },
    { emoji: "🥱", name: "yawning face", keywords: "sleep bored" },
    { emoji: "😤", name: "face with steam from nose", keywords: "triumph annoyed" },
    { emoji: "😡", name: "pouting face", keywords: "angry mad" },
    { emoji: "😠", name: "angry face", keywords: "anger upset" },
    { emoji: "🤬", name: "face with symbols on mouth", keywords: "swear rage" },
    { emoji: "😈", name: "smiling face with horns", keywords: "devil naughty" },
    { emoji: "👋", name: "waving hand", keywords: "hello bye" },
    { emoji: "🤚", name: "raised back of hand", keywords: "stop hand" },
    { emoji: "🖐️", name: "hand with fingers splayed", keywords: "high five open hand" },
    { emoji: "✋", name: "raised hand", keywords: "stop high five" },
    { emoji: "🫶", name: "heart hands", keywords: "love support" },
    { emoji: "🫰", name: "hand with index finger and thumb crossed", keywords: "money tiny heart" },
    { emoji: "👌", name: "ok hand", keywords: "okay perfect" },
    { emoji: "🤌", name: "pinched fingers", keywords: "italian gesture" },
    { emoji: "🤏", name: "pinching hand", keywords: "small little" },
    { emoji: "✌️", name: "victory hand", keywords: "peace two" },
    { emoji: "🤞", name: "crossed fingers", keywords: "luck hope" },
    { emoji: "🫠", name: "melting face", keywords: "heat awkward" },
    { emoji: "🤟", name: "love-you gesture", keywords: "ily hand sign" },
    { emoji: "🤘", name: "sign of the horns", keywords: "rock metal" },
    { emoji: "🤙", name: "call me hand", keywords: "phone shaka" },
    { emoji: "👈", name: "backhand index pointing left", keywords: "left point" },
    { emoji: "👉", name: "backhand index pointing right", keywords: "right point" },
    { emoji: "👆", name: "backhand index pointing up", keywords: "up point" },
    { emoji: "👇", name: "backhand index pointing down", keywords: "down point" },
    { emoji: "👍", name: "thumbs up", keywords: "like approve" },
    { emoji: "👎", name: "thumbs down", keywords: "dislike reject" },
    { emoji: "👏", name: "clapping hands", keywords: "applause praise" },
    { emoji: "🙌", name: "raising hands", keywords: "celebrate hooray" },
    { emoji: "🙏", name: "folded hands", keywords: "thanks please pray" },
    { emoji: "💪", name: "flexed biceps", keywords: "strong gym" },
    { emoji: "🫂", name: "people hugging", keywords: "hug support" },
    { emoji: "❤️", name: "red heart", keywords: "love like" },
    { emoji: "🩷", name: "pink heart", keywords: "love cute" },
    { emoji: "🧡", name: "orange heart", keywords: "care warm" },
    { emoji: "💛", name: "yellow heart", keywords: "friendship sunshine" },
    { emoji: "💚", name: "green heart", keywords: "nature support" },
    { emoji: "🩵", name: "light blue heart", keywords: "calm sky" },
    { emoji: "💙", name: "blue heart", keywords: "trust loyalty" },
    { emoji: "💜", name: "purple heart", keywords: "care gentle" },
    { emoji: "🖤", name: "black heart", keywords: "dark goth" },
    { emoji: "🤍", name: "white heart", keywords: "pure clean" },
    { emoji: "🤎", name: "brown heart", keywords: "earth warm" },
    { emoji: "💯", name: "hundred points", keywords: "perfect score" },
    { emoji: "✨", name: "sparkles", keywords: "magic shiny" },
    { emoji: "🔥", name: "fire", keywords: "lit hot" },
    { emoji: "⭐", name: "star", keywords: "favorite night" },
    { emoji: "🌈", name: "rainbow", keywords: "color pride" },
    { emoji: "☀️", name: "sun", keywords: "weather bright" },
    { emoji: "🌙", name: "crescent moon", keywords: "night sleep" },
    { emoji: "⚡", name: "high voltage", keywords: "energy electric" },
    { emoji: "☕", name: "hot beverage", keywords: "coffee tea" },
    { emoji: "🍕", name: "pizza", keywords: "food slice" },
    { emoji: "🍣", name: "sushi", keywords: "food japan" },
    { emoji: "🍜", name: "steaming bowl", keywords: "ramen noodles" },
    { emoji: "🍔", name: "hamburger", keywords: "burger food" },
    { emoji: "🎉", name: "party popper", keywords: "celebrate confetti" },
    { emoji: "🎂", name: "birthday cake", keywords: "cake celebration" },
    { emoji: "🎁", name: "wrapped gift", keywords: "present box" },
    { emoji: "🚀", name: "rocket", keywords: "launch ship" },
    { emoji: "💻", name: "laptop", keywords: "computer code" },
    { emoji: "📱", name: "mobile phone", keywords: "smartphone call" }
]

function getItems(query) {
    const needle = (query || "").trim().toLowerCase()
    return EMOJIS.filter((entry) => {
        if (!needle) {
            return true
        }
        return entry.name.indexOf(needle) !== -1 || entry.keywords.indexOf(needle) !== -1
    }).map((entry) => ({
        emoji: entry.emoji,
        name: entry.name,
        icon: "unicode:" + entry.emoji,
        comment: entry.keywords,
        action: "copy:" + entry.emoji,
        categories: ["EmojiLauncher"]
    }))
}
